package: cache-warmup
version: '1.0.0-beta2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cache-warmup

page:
    title: translate:title
    perm: admin
    popup: true
    hidden: true

pages:
    system/cache-warmup:
        title: translate:title
        perm: admin
    warmup:
        title: translate:title
        perm: admin
        popup: true
        hidden: true
    generator:
        title: generator
        perm: admin
        hidden: true
        hasLayout: false

requires:
    redaxo: '>=5.0'