package: cache-warmup
version: '1.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cache-warmup

page:
    title: translate:title
    perm: admin
    popup: true
    hidden: true

pages:
    system/cache-warmup:
        title: translate:title
        perm: admin
    warmup:
        title: translate:title
        perm: admin
        popup: true
        hidden: true

requires:
    redaxo: ^5.0
    packages:
        media_manager: ^2.0
    php:
        extensions: [gd]