package: cache-warmup
version: '1.0.0-beta4'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cache-warmup

page:
    title: translate:title
    perm: admin
    popup: true
    hidden: true
    subpages:
        warmup:
            title: translate:title
            popup: true
            hidden: true
        generator:
            title: generator
            hidden: true
            hasLayout: false

pages:
    system/cache-warmup:
        title: translate:title
        perm: admin

requires:
    redaxo: '^5.0'
